language: node_js
node_js:
  - "node"
jobs:
  include:
    - script: npm test && npm run lint --no-fix && npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  repo: JMLegere/jmlegere.github.io
  target_branch: master
  verbose: true
  local_dir: dist/
  fqdn: jeremylegere.com
  on:
    branch: master
    
